apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flex-authentication-pvc
  namespace: flex-authentication
    labels:
    app: flex-authentication
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M