apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flex-authentication-pvc
  namespace: flex-authentication
    labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M