apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: flex-authentication
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"