apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flex-parking-space-pvc
  namespace: flex-parking-space
  labels:
    app: flex-parking-space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M