apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flex-app
  namespace: flex-app
spec:
  secretName: flex-app
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - app.flex.tschumi.me