apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flex-test-office-booking-pvc
  namespace: flex-test-office-booking
  labels:
    app: flex-test-office-booking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M