apiVersion: v1
kind: Service
metadata:
  name: flex-test-postgres-office-booking
  namespace: flex-test-office-booking
spec:
  selector:
    app: flex-test-postgres-office-booking
  type: ClusterIP
  ports:
    - name: http
      port: 5432
