apiVersion: apps/v1
kind: Deployment
metadata:
  name: flex-app-parking-space
  namespace: flex-parking-space
  labels:
    app: flex-parking-space
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: flex-parking-space
  replicas: 1
  template:
    metadata:
      labels:
        app: flex-parking-space
    spec:
      imagePullSecrets:
      - name: github-secret
      containers:
      - name: flexoffice-parking-space
        image: ghcr.io/jonastschumi/flexoffice_parking-space:0.0.63
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: flex-parking-space-db
              key: dbname
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: flex-parking-space-db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flex-parking-space-db
              key: password
        - name: DB_HOST
          value: flex-postgres-parking-space
