apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx1
  namespace: nginx1-test
spec:
  secretName: nginx1-test
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - test1.tschumi.me