apiVersion: apps/v1
kind: Deployment
metadata:
  name: flex-test-postgres-parking-space
  namespace: flex-test-parking-space
  labels:
    app: flex-test-postgres-parking-space
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: flex-test-postgres-parking-space
  replicas: 1
  template:
    metadata:
      labels:
        app: flex-test-postgres-parking-space
    spec:
      containers:
      - name: postgres
        image: postgres:15.2-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: flex-test-parking-space-db
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: flex-test-parking-space-db
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flex-test-parking-space-db
              key: password
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: flex-test-parking-space-pvc
