apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  secretName: uptime-kuma
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - uptime.tschumi.me